### ISSUE TITLE
赞!

### ISSUE THREAD

**Issue by tvvocold** [1dot75cm/myrepo#1]
看到你的项目觉得很赞！
BTW,能否转载到http://star.fdzh.org

**Comment by 1dot75cm** [comment]
谢谢您的支持，之前很早就看到过您的站，它和官方是什么关系呢？属于非官方社区？
这个项目，目前还比较初级，之前在copr上编译了一些私有软件，也被删除了。基本上就分裂为free和nonfree两个源，而且el7的源也停止维护了（自己搞精力有限）。
如果能做一个类似russian repo那样，由国人维护的第三方源，也挺好的。
最后，您觉得好，可以转载，我顺便也注册一个账号，看看能提供什么帮助。

**Comment by tvvocold** [comment]
hi,由于不便在此回复，我以email方式发送了封邮件（sensor.wen#gmail.com），请问收到邮件了吗？
